# Site Information
site_name: Cryst4lliz3
site_author: Ahmad A'fif
site_url: https://cryst4lliz3.github.io/

# Page tree
nav:
  - Home: index.md
  - Notes: 
  - Write-up:
    - Malware Analysis:
      - Chake Berberian Order.exe: writeup/basic-malware-analysis-chake-berberian-order.md
    - CTF Intern:
      - CTF Round 3 - Active Directory: writeup/ctf-round-3-active-directory.md
    - CyberDefenders:
      - Malware Traffic Analysis 1 - PCAP: writeup/malware-traffic-analysis-1-pcap.md
    - Vulnhub:
      - VulnHub - My Web Server:1: writeup/vulnhub-my-web-server-1.md

# Configuration
theme: 
  name: material 

extra:
  disqus: cryst4lliz3-github-io