# Site Information
site_name: Cryst4lliz3
site_description: newbie in cybersec
site_author: Ahmad A'fif

# Page tree
nav:
  - Home: index.md
  - Write-up:
    - Basic Malware Analysis:
      - Chake Berberian Order.exe: writeup/basic-malware-analysis-chake-berberian-order.md
    - CTF Intern:
      - CTF Round 3 - Active Directory: writeup/ctf-round-3-active-directory.md
    - CyberDefenders:
      - Malware Traffic Analysis 1 - PCAP: writeup/malware-traffic-analysis-1-pcap.md

# Configuration
theme: 
  name: material 

# Analytics
google_analytics:
  - UA-183966884-1
  - auto

extra:
  generator: false
  disqus: cryst4lliz3-github-io